# We will cover most fundamental concepts of Tensors using TensorFlow


*   Introductin to Tensors
*   Getting information from tensors
*   Manipulating Tensors
*   Tesnsors & Numpy
*   Using @tf.function (way to speedup regular python funciton)
*   Using GPU/TPU with tensors



In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(21)
print(scalar)


tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
scalar.ndim

0

In [ ]:
tf.constant(7, shape = (3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [ ]:
myconst = tf.constant([1,2,3,4,5,6], shape =[3,2], dtype=tf.float64)
myconst

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]])>

In [ ]:
# Check the number of dimensions of a tensor
myconst.ndim

2

In [ ]:
tf.constant(7, shape = (3,3)).ndim

2

In [ ]:
vector = tf.constant([1,2,3,4,5,6])
vector

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Creating a matrix
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
print(scalar)

tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
print("scalar has {} dimensions".format(scalar.ndim))

scalar has 0 dimensions


In [ ]:
print(f'scalar has {scalar.ndim} dimensions.\nVector has {vector.ndim} dimenssions. \nMatrix has {matrix.ndim} dimensions', )

scalar has 0 dimensions.
Vector has 1 dimenssions. 
Matrix has 2 dimensions


In [ ]:
# Creating a tensor
mytensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])


In [ ]:
print(mytensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(mytensor.ndim)

3


*  Scalar is a single number
*  Vector is a number with the direction such as car speed & direction
*  Matrix is a 2-dimensional array of numbers
*  Tensor is an n dimensional array of numbers where n can be 0 dimension is scalar, 1 dimension is vector, 2 dimension is matrix etc

### Creating tensor with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Creating Variables means that can be updated unlike tf.Constant

changeable_tensor = tf.Variable([9,8,7])
unchangeable_tensor = tf.constant([9,8,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([9, 8, 7], dtype=int32)>
tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [ ]:
# Lets try to change or update changeable tensor
changeable_tensor[0], changeable_tensor[1]

(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [ ]:
# You can't assign or update value using = . We should use assign()
# Using .assign for update
changeable_tensor[0].assign(99)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([99,  8,  7], dtype=int32)>

In [ ]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([99,  8,  7], dtype=int32)>

In [ ]:
# Lets try to update unchangeable tensor that is constant
# ---unchangeable_tensor[0].assign(99)

In [ ]:
# Lets try to update unchangeable tensor that is constant
# ---unchangeable_tensor[0] = 99

### Creating Random Tensors

In [ ]:
random01 = tf.random.Generator.from_seed(101)
random01
random02 = random01.uniform(shape = (2,2))
random02
random03 = random01.uniform(shape = (2,2))
random03

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.96239614, 0.9685962 ],
       [0.42677665, 0.23815608]], dtype=float32)>

In [ ]:
random02==random03

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [ ]:
random01 = tf.random.Generator.from_seed(101)
random02 = random01.uniform(shape = (2,2))

random03 = random01.uniform(shape = (2,2))
random02, random03

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.22709787, 0.49256873],
        [0.7682668 , 0.8009803 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.96239614, 0.9685962 ],
        [0.42677665, 0.23815608]], dtype=float32)>)

In [ ]:
random01 = tf.random.Generator.from_seed(101)
random03 = random01.uniform(shape = (2,2))
random03
random02 = tf.random.Generator.from_seed(101)
random04 = random02.uniform(shape = (2,2))
random03, random04

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.22709787, 0.49256873],
        [0.7682668 , 0.8009803 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.22709787, 0.49256873],
        [0.7682668 , 0.8009803 ]], dtype=float32)>)

In [ ]:
random03 == random04

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
random03 = tf.random.normal(shape=(2,2))
random03

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.42603362, -1.685729  ],
       [ 0.6584978 , -0.62915367]], dtype=float32)>

In [ ]:
 tf.random.Generator.from_seed(101)

In [ ]:
random03 = tf.random.normal(shape=(2,2))
random03

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.20073715,  0.29278937],
       [ 1.7471745 ,  0.14574437]], dtype=float32)>

## Shuffle the order of elements of a tensor

In [ ]:
not_shuffled = tf.constant([1,2,3,4])
not_shuffled 

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled  

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 4], dtype=int32)>

In [ ]:
ns = tf.constant([[[1,2,3],
                  [4,5,6],
                 [7,8,9]]])
ns

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
shuf = tf.random.shuffle(ns)
shuf

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
ns = tf.constant([[1,2],
                  [4,5],
                 [7,8]])
ns

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [ ]:
shuf = tf.random.shuffle(ns)
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [7, 8]], dtype=int32)>

In [ ]:
shuf = tf.random.shuffle(ns)
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [ ]:
shuf = tf.random.shuffle(ns, seed = 101) # Operation Level Random Seed
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
tf.random.set_seed(101) # Global Level Random Seed
shuf = tf.random.shuffle(ns) 
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [4, 5]], dtype=int32)>

## Creating Tensors Using like Numpy Array

In [ ]:
# Creating a tensors of all 1s
tf.ones(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
# Creating a tensors of all 1s
tf.ones([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating a tensors of all 0s
tf.zeros([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones(shape = (4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Turning Numpy Arrays into Tensors
import numpy as np


In [ ]:
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
tensor_va = tf.Variable(numpy_A)
tensor_va

<tf.Variable 'Variable:0' shape=(24,) dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
# Changing the shape 
A = tf.constant(numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [ ]:
# Changing the shape 
A = tf.constant(numpy_A, shape = (6,4))
A

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

## Getting Information from Tensor

In [ ]:
### The difference between a NumPy array and a tensor is that the tensors
### are backed by the accelerator memory like GPU and they are immutable, unlike NumPy arrays.

* Shape - The lenght ( No. of elements) of each  of the dimensions of a tensor - No. of elements in each dimension
* Rank - No. of tensor dimensions. A scalar has rank 0, Vector has rank 1 & Matrix has rank 2, a tensor has rank n
* Dimension or axis - A particular dimension of a tensor
* Size - The total number of items in the tensor


---



* Shape - tensor.shape
* Rank - tensor.ndim
* Axis or Dimension - Tensor[0], tensor[:, 1]...tensor[:n]
* Size - tf.size(tensor)

In [ ]:
# Creating a rank 4 tensor 
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Shape - The lenght ( No. of elements) of each  of the dimensions of a tensor
# Rank - No. of tensor dimensions. A scalar has rank 0, Vector has rank 1 & Matrix has rank 2, a tensor has rank n
# Dimension or axis - A particular dimension of a tensor
# Size - The total number of items in the tensor
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)
# Shape - [2,3,4,5]
# Rank - 4
# Size - 2*3*4*5 = 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Data type of elements of tensor
rank_4_tensor.dtype

tf.float32

In [ ]:
# Elements along the zero axis
rank_4_tensor.shape[0]

2

In [ ]:
# Elements along the last axis
rank_4_tensor.shape[-1]

5

In [ ]:
# Elements along the last axis
rank_4_tensor.shape[3]

5

In [ ]:
# Coverting to numpy
tf.size(rank_4_tensor).numpy()

120

## Indexing & Expanding Tensors

In [ ]:
# Getting the 1st two elements
mylist = [1,2,3]
mylist[:2]

[1, 2]

In [ ]:
# Getting the 1st two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
myarr = np.arange(1,121)

In [ ]:
myarr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120])

In [ ]:
mytensor = tf.constant(myarr, shape = [2,3,4,5])
mytensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [ ]:
# Selecting only 1st two elements from each dimension
mytensor[:2,:2,:2,:2]

# focus on shape of the output to understand the result

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]])>

In [ ]:
# Get the first element from each dimension except for the last one
mytensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [ ]:
mytensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [ ]:
mytensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int64, numpy=
array([[[[ 1],
         [ 6],
         [11],
         [16]]]])>

In [ ]:
rank2 = tf.constant([[1,2],[3,4]])
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank2.ndim

2

In [ ]:
# selecting last element of each row
rank2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Adding new dimension to the existing tensor
rank2.shape

TensorShape([2, 2])

In [ ]:
# Adding axis to the end
rank2[...,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
rank2[:,tf.newaxis]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [ ]:
rank2[:,:,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank2, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank2, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

## Manipulating Tensors
### Basic Operations such as 
* addition
* subtraction
* multiplicaiton
* division

In [ ]:
mytensor = tf.constant([[1,2],[3,4]])
mytensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
mytensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
mytensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
mytensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.multiply(mytensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tf.add(mytensor , 1000)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1001, 1002],
       [1003, 1004]], dtype=int32)>

## **Tensor Multiplication**  
* Dot Product - 1st row multiplied & added to 1st column
* The inner dimension must match
* The resulting matrix has the shape of outer dimensions


In [ ]:
# Gives the dot product
tf.matmul(mytensor, mytensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
mytensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
mytensor* mytensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
# Matrix multiplication with python @ operator
# Dot product
mytensor @ mytensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,2,3],
                       [4,5,6]])
tensor2 = tf.constant([[7,8,9],
                       [10,11,12]])

In [ ]:
tensor1.shape, tensor2.shape

(TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
# Here dot product will not work as inner dimension are not same
# We need to change the dimensions of one of the matrix
tensor3 = tf.reshape(tensor2, shape = (3,2))
tensor3.shape

TensorShape([3, 2])

In [ ]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tensor1 @ tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
new_tensor = tf.matmul(tensor1, tensor3)
new_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
new_tensor.shape

TensorShape([2, 2])

In [ ]:
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# In transpose we flip the axes
tf.transpose(tensor1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.tensordot(tensor1, tensor3, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

**We generally transpose the matrix for dot product to match the inner dimension**

# Changing the datatype of tensors

In [ ]:
# Creating a tensor with default datatype
# Default float is float32

tensor01 = tf.constant([1.8, 1.1])
tensor01

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.8, 1.1], dtype=float32)>

In [ ]:
tensor01.dtype

tf.float32

In [ ]:
tensor02 = tf.constant([18, 19])
print(tensor02)
print(tensor02.dtype)

tf.Tensor([18 19], shape=(2,), dtype=int32)
<dtype: 'int32'>


In [ ]:
tensor03 = tf.constant(['hi','hello'])
tensor03

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hi', b'hello'], dtype=object)>

In [ ]:
tensor03.dtype

tf.string

In [ ]:
# Changing the data type precision from float32 to float16
# For this we will use cast
tensor16 = tf.cast(tensor01, dtype = tf.float16)
tensor16.dtype, tensor16

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.8, 1.1], dtype=float16)>)

In [ ]:
# Changing data type from int to float
tf.cast(tensor02, dtype = tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([18., 19.], dtype=float16)>

# Tensor Aggrigating - Min, Max, Mean etc

In [ ]:

tensor = tf.constant([-1,3,-99])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -1,   3, -99], dtype=int32)>

In [ ]:
# Aboslute Values
tf.abs(tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1,  3, 99], dtype=int32)>

In [ ]:
# Getting the min of tensor
# tf.reduce_min
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-99>

In [ ]:
# Getting the max
# tf.reduce_max
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Getting the mean
# tf.reduce_mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-32>

In [ ]:
# Getting the var
# tf.nn.moments
mean, var = tf.nn.moments(tensor, axes=0)
mean, var

(<tf.Tensor: shape=(), dtype=int32, numpy=-32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2225>)

In [ ]:
# Getting the sum 
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-97>

In [ ]:
# Importing tensorflow probability
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(tensor, sample_axis = 0)

<tf.Tensor: shape=(), dtype=int32, numpy=2225>

In [ ]:
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2225>

In [ ]:
tf.math.reduce_std(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=47.16873>

# Positional Min & Max of a tensor (Argmin & Argmax)

In [ ]:
tensor = tf.random.uniform(shape = [50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.89634764, 0.43632448, 0.2869135 , 0.55935633, 0.8520273 ,
       0.24758482, 0.73670137, 0.7737043 , 0.8227066 , 0.50050473,
       0.07754254, 0.05552638, 0.7436762 , 0.53811586, 0.9549563 ,
       0.53353775, 0.6845912 , 0.3955264 , 0.6545265 , 0.21328223,
       0.14219534, 0.60913014, 0.00589144, 0.8652122 , 0.8633505 ,
       0.10108292, 0.7004198 , 0.8650571 , 0.6628951 , 0.49752378,
       0.05483806, 0.9541081 , 0.5460985 , 0.7921268 , 0.19075882,
       0.04708636, 0.7742598 , 0.30114508, 0.86187387, 0.9810579 ,
       0.63391066, 0.7327409 , 0.61038625, 0.7539878 , 0.9439794 ,
       0.7979953 , 0.2046516 , 0.00662291, 0.5658374 , 0.8496262 ],
      dtype=float32)>

In [ ]:
# Finding the max value
tfmax = tf.reduce_max(tensor)
tfmax

<tf.Tensor: shape=(), dtype=float32, numpy=0.9810579>

In [ ]:
# Finding the position of max value
# Using argmax
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [ ]:
tensor[39]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9810579>

In [ ]:
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9810579>

In [ ]:
assert tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)
# No error implies correct

In [ ]:
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Finding the position of min value
# Using argmin

tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [ ]:
tensor[22]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0058914423>

## Squeezing a Tensor - removing all single dimensions
* Removes dimensions of size 1 from the shape of the tensor

In [ ]:
tensor  = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6705607 , 0.74372625, 0.5481626 , 0.06909919, 0.11069727,
           0.39205885, 0.306049  , 0.35925663, 0.01049483, 0.95366585,
           0.7413583 , 0.7640557 , 0.7420757 , 0.6912377 , 0.8296976 ,
           0.51758516, 0.5600425 , 0.40601647, 0.6724334 , 0.08109951,
           0.1434015 , 0.5693476 , 0.65937245, 0.4562862 , 0.11684513,
           0.71968114, 0.94774616, 0.98971605, 0.90619516, 0.39798272,
           0.49667346, 0.9406822 , 0.2973386 , 0.7948183 , 0.86289525,
           0.5081961 , 0.8249029 , 0.89208364, 0.7267214 , 0.61645615,
           0.41040277, 0.35164595, 0.4380983 , 0.14819062, 0.20153832,
           0.8433814 , 0.57373345, 0.6411717 , 0.7194518 , 0.75309896]]]]],
      dtype=float32)>

In [ ]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
tensor.ndim

5

In [ ]:
tensor_squeeze = tf.squeeze(tensor)
tensor_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6705607 , 0.74372625, 0.5481626 , 0.06909919, 0.11069727,
       0.39205885, 0.306049  , 0.35925663, 0.01049483, 0.95366585,
       0.7413583 , 0.7640557 , 0.7420757 , 0.6912377 , 0.8296976 ,
       0.51758516, 0.5600425 , 0.40601647, 0.6724334 , 0.08109951,
       0.1434015 , 0.5693476 , 0.65937245, 0.4562862 , 0.11684513,
       0.71968114, 0.94774616, 0.98971605, 0.90619516, 0.39798272,
       0.49667346, 0.9406822 , 0.2973386 , 0.7948183 , 0.86289525,
       0.5081961 , 0.8249029 , 0.89208364, 0.7267214 , 0.61645615,
       0.41040277, 0.35164595, 0.4380983 , 0.14819062, 0.20153832,
       0.8433814 , 0.57373345, 0.6411717 , 0.7194518 , 0.75309896],
      dtype=float32)>

In [ ]:
tensor_squeeze.shape

TensorShape([50])

In [ ]:
tensor_squeeze.ndim

1

## One-Hot Encoding Tensors

In [ ]:
# Create a list 
mylist = [1,2,3,4] # think of it as a red, blue, gree, yellow

# Creating a one-hot enoder for the mylist
tf.one_hot(mylist, depth = 4 )

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one-hot encoding
tf.one_hot(mylist, depth = 4, on_value='one I like', off_value='zero' )

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'zero', b'one I like', b'zero', b'zero'],
       [b'zero', b'zero', b'one I like', b'zero'],
       [b'zero', b'zero', b'zero', b'one I like'],
       [b'zero', b'zero', b'zero', b'zero']], dtype=object)>

## Math Operations
* Square
* Square root
* log

In [ ]:
newtensor = tf.range(10)
newtensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(newtensor)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square Root
tf.sqrt(tf.cast(newtensor, dtype = tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

In [ ]:
# Log
tf.math.log(tf.cast(newtensor, dtype = tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors & Numpy Compatibility

In [ ]:
# Creating a tensor from numpy
tensor = tf.constant(np.array([1,2,3,4]))
tensor

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
# Creating a numpy array from tensor
myarr = np.array(tensor)
myarr

array([1, 2, 3, 4])

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
tensor.numpy()

array([1, 2, 3, 4])

In [ ]:
tensor.numpy()[2]

3

In [ ]:
# Default dtype will be different when we create tensor from numpy 
tensor = tf.constant(np.array([1,2,3,4]))
tensor.dtype

tf.int64

In [ ]:
newtensor = tf.constant([1,2,3,4])
newtensor.dtype

tf.int32

# Finding access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

